Optimizer
CEA-COSMIC/pysap-mri pull request #134
Opened 2021-12-01 10:39 UTC by paquiteau

2021-12-01 12:52 UTC, paquiteau commented
Don't Worry, the test are coming with the PR for reconstructors.

2021-12-01 14:17 UTC, chaithyagr commented
Added @Daval-G for review.

2021-12-03 08:55 UTC, Daval-G requested changes
It looks good to me, aside from minor typos. However it would be nice to add some minimal tests.

2021-12-03 08:55 UTC, Daval-G commented on mri/optimizers/base.py
> +    estimate_call_period: int, default None
Also it would be nice to know the `kspace_generator` and `opt` types.

2021-12-03 08:55 UTC, Daval-G commented on mri/optimizers/utils/cost.py
> +                # synthesis case, this already in the linear_op (sparse) domain.
Missing words

2021-12-03 10:56 UTC, paquiteau commented
To add test on the online algorithms similar to the existing one for the offline algorithms I will need to add the [OnlineReconstructor](https://github.com/paquiteau/pysap-mri-online/blob/master/online/reconstructors/reconstructor.py), which need  the generator PR to be merge, and Ideally my PR on Modopt for gradient descent algorithms, to have a complete picture.

2021-12-06 08:22 UTC, chaithyagr commented
> To add test on the online algorithms similar to the existing one for the offline algorithms I will need to add the [OnlineReconstructor](https://github.com/paquiteau/pysap-mri-online/blob/master/online/reconstructors/reconstructor.py), which need the generator PR to be merge, and Ideally my PR on Modopt for gradient descent algorithms, to have a complete picture.

In my opinion, we can wait for those PRs to go through. In the meantime, @paquiteau do keep the tests ready. Once other PRs are done, we can test finally and submit. Sounds good?

2021-12-06 08:23 UTC, chaithyagr commented
other option is to write it as TODO, open a new issue and make sure it is done later.

2021-12-10 13:51 UTC, Daval-G approved these changes
Seems good to merge, besides some quick comment to address

2021-12-10 15:20 UTC, merged